spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr:
server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS