nacos:
  config:
    gateway:
      route:
        dataId: gateway-routes
        groupId: DEFAULT_GROUP
spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    baseUrl: http://prophet-zipkin-server/
    enabled: true
    discovery-client-enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
gateway:
  blacklists:
    - uri:
        /authority/api/demo1
      ips:
        - 172.20.8.104
    - uri:
        /api/demo1
      ips:
        - 127.0.0.1
