spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    baseUrl: http://prophet-zipkin-server/
    enabled: true
    discovery-client-enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9999
      # 开启懒加载
      eager: true
  datasource:
    url: jdbc:mysql://localhost:3306/authority?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 86430000
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource